"""
Reports page for SwiftLedger.

Generates branded PDF statements:
  - Individual member ledger (savings + loans)
  - Society-wide financial summary
  - Auto-launch Quick Start Manual

PDFs feature colour-coded rows, a dynamic header (logo or society name),
and the "Generated by SwiftLedger - Developed by Zabdiel" footer.
"""

import sys
import os
import platform
import subprocess
import tempfile
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional

from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton,
    QGroupBox, QFormLayout, QLineEdit, QMessageBox,
    QFileDialog,
)
from PySide6.QtCore import Qt
from PySide6.QtGui import QFont

sys.path.insert(0, str(Path(__file__).parent.parent))
from database.queries import (
    get_system_settings, get_member_by_staff_number,
    get_member_savings, get_member_loans, get_society_stats,
    get_all_members,
)
from database.db_init import log_event


class ReportsPage(QWidget):
    """Branded PDF report generator with member ledger and society summary."""

    def __init__(self, db_path: str = "swiftledger.db"):
        super().__init__()
        self.db_path = db_path
        self._build_ui()

    # ── UI ───────────────────────────────────────────────────────────

    def _build_ui(self) -> None:
        main = QVBoxLayout(self)
        main.setContentsMargins(20, 20, 20, 20)
        main.setSpacing(20)

        # Title
        title = QLabel("Reports")
        tf = QFont("Arial", 18)
        tf.setBold(True)
        title.setFont(tf)
        main.addWidget(title)

        # ── Member Ledger ────────────────────────────────────────────
        ledger_group = QGroupBox("Member Statement")
        ledger_group.setFont(QFont("Arial", 12))
        ledger_form = QFormLayout(ledger_group)
        ledger_form.setContentsMargins(14, 20, 14, 14)
        ledger_form.setSpacing(12)

        self.input_staff = QLineEdit()
        self.input_staff.setPlaceholderText("e.g., EMP001")
        ledger_form.addRow("Staff Number:", self.input_staff)

        self.btn_member_preview = QPushButton("Preview Member Statement")
        self.btn_member_preview.setMinimumHeight(38)
        self.btn_member_preview.setCursor(Qt.CursorShape.PointingHandCursor)
        self.btn_member_preview.setStyleSheet(
            "QPushButton { background-color: #2980b9; color: white; "
            "border-radius: 6px; padding: 8px 20px; font-weight: bold; } "
            "QPushButton:hover { background-color: #3498db; }"
        )
        self.btn_member_preview.clicked.connect(self._preview_member_pdf)

        self.btn_member_pdf = QPushButton("Save Member Statement PDF")
        self.btn_member_pdf.setMinimumHeight(38)
        self.btn_member_pdf.setCursor(Qt.CursorShape.PointingHandCursor)
        self.btn_member_pdf.setStyleSheet(
            "QPushButton { background-color: #34495e; color: white; "
            "border-radius: 6px; padding: 8px 20px; font-weight: bold; } "
            "QPushButton:hover { background-color: #3b5770; }"
        )
        self.btn_member_pdf.clicked.connect(self._generate_member_pdf)

        member_actions = QHBoxLayout()
        member_actions.addWidget(self.btn_member_preview)
        member_actions.addWidget(self.btn_member_pdf)
        ledger_form.addRow(member_actions)

        main.addWidget(ledger_group)

        # ── Society Summary ──────────────────────────────────────────
        summary_group = QGroupBox("Society Financial Summary")
        summary_group.setFont(QFont("Arial", 12))
        summary_layout = QVBoxLayout(summary_group)
        summary_layout.setContentsMargins(14, 20, 14, 14)

        self.btn_society_preview = QPushButton("Preview Society Summary")
        self.btn_society_preview.setMinimumHeight(38)
        self.btn_society_preview.setCursor(Qt.CursorShape.PointingHandCursor)
        self.btn_society_preview.setStyleSheet(
            "QPushButton { background-color: #27ae60; color: white; "
            "border-radius: 6px; padding: 8px 20px; font-weight: bold; } "
            "QPushButton:hover { background-color: #2ecc71; }"
        )
        self.btn_society_preview.clicked.connect(self._preview_society_pdf)

        self.btn_society_pdf = QPushButton("Save Society Summary PDF")
        self.btn_society_pdf.setMinimumHeight(38)
        self.btn_society_pdf.setCursor(Qt.CursorShape.PointingHandCursor)
        self.btn_society_pdf.setStyleSheet(
            "QPushButton { background-color: #1f6f3e; color: white; "
            "border-radius: 6px; padding: 8px 20px; font-weight: bold; } "
            "QPushButton:hover { background-color: #24814a; }"
        )
        self.btn_society_pdf.clicked.connect(self._generate_society_pdf)

        summary_actions = QHBoxLayout()
        summary_actions.addWidget(self.btn_society_preview)
        summary_actions.addWidget(self.btn_society_pdf)
        summary_layout.addLayout(summary_actions)

        main.addWidget(summary_group)
        main.addStretch()

    # ── Helpers ──────────────────────────────────────────────────────

    def _get_fpdf(self):
        """Return the FPDF class or None if unavailable."""
        try:
            from fpdf import FPDF
            return FPDF
        except ImportError:
            QMessageBox.critical(
                self, "Missing Library",
                "Install fpdf2 to generate PDFs:\n  pip install fpdf2"
            )
            return None

    def _society_header(self) -> dict:
        """Return society branding info from settings."""
        ok, s = get_system_settings(self.db_path)
        if ok and s:
            return {
                "name": s.get("society_name") or "SwiftLedger",
                "street": s.get("street") or "",
                "city": s.get("city_state") or "",
                "phone": s.get("phone") or "",
                "email": s.get("email") or "",
                "reg_no": s.get("reg_no") or "",
                "logo": s.get("logo_path") or "",
            }
        return {"name": "SwiftLedger", "street": "", "city": "",
                "phone": "", "email": "", "reg_no": "", "logo": ""}

    def _add_header(self, pdf, info: dict) -> None:
        """Add dynamic branded header (logo or styled society name)."""
        logo = info.get("logo", "")
        if logo and Path(logo).is_file():
            try:
                pdf.image(logo, x=10, y=8, w=30)
                pdf.set_xy(45, 8)
            except Exception:
                pass

        pdf.set_font("Helvetica", "B", 18)
        pdf.cell(0, 10, info["name"], new_x="LMARGIN", new_y="NEXT", align="C")

        details = []
        if info["street"]:
            details.append(info["street"])
        if info["city"]:
            details.append(info["city"])
        if info["phone"]:
            details.append(f"Tel: {info['phone']}")
        if info["email"]:
            details.append(info["email"])
        if info["reg_no"]:
            details.append(f"Reg: {info['reg_no']}")

        if details:
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 6, "  |  ".join(details), new_x="LMARGIN", new_y="NEXT", align="C")

        pdf.ln(4)
        pdf.set_draw_color(52, 73, 94)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

    def _add_footer_text(self, pdf) -> None:
        pdf.ln(8)
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(
            0, 8,
            f"Generated by SwiftLedger - Developed by Zabdiel  |  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            align="C",
        )

    def _open_pdf_preview(self, path: str) -> None:
        """Show an in-app PDF viewer dialog."""
        try:
            from PySide6.QtPdf import QPdfDocument
            from PySide6.QtPdfWidgets import QPdfView
            from PySide6.QtWidgets import QDialog
        except ImportError:
            QMessageBox.information(
                self,
                "Preview Unavailable",
                "PDF preview requires Qt PDF modules.\n"
                "Please update PySide6 or open the file with an external viewer.",
            )
            return

        dialog = QDialog(self)
        dialog.setWindowTitle("PDF Preview")
        dialog.resize(900, 700)
        layout = QVBoxLayout(dialog)

        pdf_doc = QPdfDocument(dialog)
        status = pdf_doc.load(path)
        if status != QPdfDocument.Status.Ready:
            QMessageBox.warning(self, "Preview Error", "Unable to load the PDF file.")
            return

        view = QPdfView(dialog)
        view.setDocument(pdf_doc)
        view.setPageMode(QPdfView.PageMode.MultiPage)
        layout.addWidget(view)

        dialog.setProperty("pdf_doc", pdf_doc)
        dialog.exec()

    def _write_pdf_to_path(self, pdf, path: str) -> bool:
        """Persist an FPDF object to disk and return success state."""
        try:
            content = pdf.output(dest="S")
            if isinstance(content, str):
                data = content.encode("latin-1")
            else:
                data = bytes(content)

            if not data:
                return False

            with open(path, "wb") as f:
                f.write(data)
            return True
        except Exception:
            return False

    # ── Build PDF objects (shared by preview & save) ─────────────────

    def _build_member_pdf(self, staff: str):
        """
        Build a member statement PDF in memory.

        Returns (pdf_object, member_dict) or (None, None) on failure.
        """
        ok, member = get_member_by_staff_number(self.db_path, staff)
        if not ok or not member:
            QMessageBox.warning(self, "Not Found", f"No member with staff number '{staff}'.")
            return None, None

        member = dict(member)

        FPDF = self._get_fpdf()
        if not FPDF:
            return None, None

        mid = member.get("member_id")
        if not mid:
            QMessageBox.warning(self, "Error", "Member record is missing an ID.")
            return None, None
        _, savings_txns = get_member_savings(self.db_path, mid)
        _, loans = get_member_loans(self.db_path, mid)
        info = self._society_header()

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        # Header
        self._add_header(pdf, info)

        # Member info
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, f"Statement for: {member.get('full_name', '')} ({staff})",
             new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        savings_bal = float(member.get("current_savings", 0) or 0)
        loans_bal = float(member.get("total_loans", 0) or 0)
        pdf.cell(0, 6, f"Current Savings: NGN {savings_bal:,.2f}   |   Outstanding Loans: NGN {loans_bal:,.2f}",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # Savings table
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Savings Transactions", new_x="LMARGIN", new_y="NEXT")
        col_w = [40, 28, 32, 36]
        headers = ["Date", "Type", "Amount", "Balance"]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(44, 62, 80)
        pdf.set_text_color(255, 255, 255)
        for w, h in zip(col_w, headers):
            pdf.cell(w, 7, h, border=1, fill=True, align="C")
        pdf.ln()
        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Helvetica", "", 7)
        for i, tx in enumerate(savings_txns):
            if i % 2 == 0:
                pdf.set_fill_color(236, 240, 241)
            else:
                pdf.set_fill_color(255, 255, 255)

            ttype = str(tx.get("trans_type", ""))
            if ttype == "Lodgment":
                pdf.set_text_color(39, 174, 96)
            elif ttype == "Deduction":
                pdf.set_text_color(231, 76, 60)
            else:
                pdf.set_text_color(0, 0, 0)

            vals = [
                str(tx.get("trans_date", ""))[:19],
                ttype,
                f"NGN {float(tx.get('amount', 0)):,.2f}",
                f"NGN {float(tx.get('running_balance', 0)):,.2f}",
            ]
            for w, v in zip(col_w, vals):
                pdf.cell(w, 6, v, border=1, fill=True)
            pdf.ln()
        pdf.set_text_color(0, 0, 0)

        if not savings_txns:
            pdf.cell(sum(col_w), 6, "No savings transactions found", border=1, align="C")
            pdf.ln()

        pdf.ln(4)

        # Loans table
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Loan Records", new_x="LMARGIN", new_y="NEXT")
        loan_w = [20, 32, 28, 24, 36]
        loan_h = ["ID", "Principal", "Rate", "Status", "Date Issued"]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(44, 62, 80)
        pdf.set_text_color(255, 255, 255)
        for w, h in zip(loan_w, loan_h):
            pdf.cell(w, 7, h, border=1, fill=True, align="C")
        pdf.ln()
        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Helvetica", "", 7)
        for i, loan in enumerate(loans):
            if i % 2 == 0:
                pdf.set_fill_color(236, 240, 241)
            else:
                pdf.set_fill_color(255, 255, 255)

            status = str(loan.get("status", ""))
            if status == "Active":
                pdf.set_text_color(39, 174, 96)
            elif status in ("Default", "Overdue"):
                pdf.set_text_color(231, 76, 60)
            else:
                pdf.set_text_color(0, 0, 0)

            vals = [
                str(loan.get("loan_id", "")),
                f"NGN {float(loan.get('principal', 0)):,.2f}",
                f"{float(loan.get('interest_rate', 0)):.1f}%",
                status,
                str(loan.get("date_issued", ""))[:10],
            ]
            for w, v in zip(loan_w, vals):
                pdf.cell(w, 6, v, border=1, fill=True)
            pdf.ln()
        pdf.set_text_color(0, 0, 0)

        if not loans:
            pdf.cell(sum(loan_w), 6, "No loan records found", border=1, align="C")
            pdf.ln()

        self._add_footer_text(pdf)
        return pdf, member

    def _build_society_pdf(self, monthly_chart=None):
        """
        Build a society summary PDF in memory with optional financial health chart.

        Args:
            monthly_chart: Optional InteractiveMonthlyChart widget for embedding chart image.

        Returns pdf_object or None on failure.
        """
        FPDF = self._get_fpdf()
        if not FPDF:
            return None

        ok, stats = get_society_stats(self.db_path)
        if not ok:
            QMessageBox.critical(self, "Error", "Could not load society statistics.")
            return None

        ok_m, members = get_all_members(self.db_path)
        info = self._society_header()

        # Try to capture chart if provided
        chart_png_path = None
        if monthly_chart is not None:
            try:
                chart_png_path = monthly_chart.capture_chart()
            except Exception:
                pass

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        self._add_header(pdf, info)

        # Summary cards
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Financial Summary", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 11)
        lines = [
            f"Total Members: {stats.get('total_members', 0)}",
            f"Total Savings: NGN {stats.get('total_savings', 0):,.2f}",
            f"Total Loans Disbursed: NGN {stats.get('total_loans_disbursed', 0):,.2f}",
            f"Projected Interest: NGN {stats.get('total_projected_interest', 0):,.2f}",
            f"Members' Dividend (60%): NGN {stats.get('members_dividend_share', 0):,.2f}",
            f"Society Reserve (40%): NGN {stats.get('society_dividend_share', 0):,.2f}",
        ]
        for line in lines:
            pdf.cell(0, 7, line, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # Embed chart if available
        if chart_png_path and Path(chart_png_path).is_file():
            try:
                pdf.set_font("Helvetica", "B", 12)
                pdf.cell(0, 8, "Monthly Trends (Savings vs Loans)", new_x="LMARGIN", new_y="NEXT")
                pdf.image(chart_png_path, x=10, w=190)
                pdf.ln(4)
            except Exception:
                pass

        # Financial Health Analysis section
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Financial Health Analysis", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        
        # Import analytics for LTS and liquidity
        try:
            from logic.analytics import calculate_lts_ratio, get_liquidity_status
            lts_ok, lts_ratio = calculate_lts_ratio(self.db_path)
            liq_ok, liq_data = get_liquidity_status(self.db_path)
            
            if lts_ok and liq_ok:
                lts_status = "Low Risk" if lts_ratio <= 60 else ("Moderate Risk" if lts_ratio <= 85 else "High Risk")
                liq_ratio = liq_data.get('liquidity_ratio', 0) if liq_ok else 0
                
                analysis_lines = [
                    f"Loan-to-Savings Ratio: {lts_ratio:.1f}% ({lts_status})",
                    f"Available Cash: NGN {liq_data.get('available_cash', 0):,.2f}",
                    f"Outstanding Loans: NGN {liq_data.get('outstanding_loans', 0):,.2f}",
                    f"Liquidity Ratio: {liq_ratio:.1f}%",
                ]
                for line in analysis_lines:
                    pdf.cell(0, 6, line, new_x="LMARGIN", new_y="NEXT")
        except Exception:
            pdf.cell(0, 6, "Unable to load financial analysis data.", new_x="LMARGIN", new_y="NEXT")
        
        pdf.ln(4)

        # Member roster table
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Member Roster", new_x="LMARGIN", new_y="NEXT")
        col_w = [28, 42, 32, 32, 32]
        headers = ["Staff #", "Name", "Phone", "Savings", "Loans"]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(44, 62, 80)
        pdf.set_text_color(255, 255, 255)
        for w, h in zip(col_w, headers):
            pdf.cell(w, 7, h, border=1, fill=True, align="C")
        pdf.ln()
        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Helvetica", "", 7)
        if ok_m and members:
            for i, m in enumerate(members):
                if i % 2 == 0:
                    pdf.set_fill_color(236, 240, 241)
                else:
                    pdf.set_fill_color(255, 255, 255)
                vals = [
                    str(m.get("staff_number", "")),
                    str(m.get("full_name", ""))[:26],
                    str(m.get("phone", "") or ""),
                    f"NGN {float(m.get('current_savings', 0) or 0):,.2f}",
                    f"NGN {float(m.get('total_loans', 0) or 0):,.2f}",
                ]
                for w, v in zip(col_w, vals):
                    pdf.cell(w, 6, v, border=1, fill=True)
                pdf.ln()

        # Clean up temporary chart PNG file
        if chart_png_path and Path(chart_png_path).is_file():
            try:
                os.unlink(chart_png_path)
            except OSError:
                pass

        self._add_footer_text(pdf)
        return pdf

    # ── Preview (build -> temp file -> in-app viewer) ────────────────

    def _preview_member_pdf(self) -> None:
        staff = self.input_staff.text().strip()
        if not staff:
            QMessageBox.warning(self, "Input Required", "Enter a staff number.")
            return

        pdf, member = self._build_member_pdf(staff)
        if pdf is None:
            return

        tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False, prefix="sl_preview_")
        tmp_path = tmp.name
        tmp.close()
        if not self._write_pdf_to_path(pdf, tmp_path):
            QMessageBox.warning(self, "Preview Error", "Unable to write preview file.")
            return

        self._open_pdf_preview(tmp_path)

        # Clean up temp file after dialog closes
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    def _preview_society_pdf(self) -> None:
        pdf = self._build_society_pdf()
        if pdf is None:
            return

        tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False, prefix="sl_preview_")
        tmp_path = tmp.name
        tmp.close()
        if not self._write_pdf_to_path(pdf, tmp_path):
            QMessageBox.warning(self, "Preview Error", "Unable to write preview file.")
            return

        self._open_pdf_preview(tmp_path)

        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    # ── Save (build -> file dialog -> write) ─────────────────────────

    def _generate_member_pdf(self) -> None:
        staff = self.input_staff.text().strip()
        if not staff:
            QMessageBox.warning(self, "Input Required", "Enter a staff number.")
            return

        pdf, member = self._build_member_pdf(staff)
        if pdf is None or member is None:
            return

        path, _ = QFileDialog.getSaveFileName(
            self, "Save Member Statement",
            f"SwiftLedger_Statement_{staff}.pdf", "PDF Files (*.pdf)",
        )
        if not path:
            return

        if not self._write_pdf_to_path(pdf, path):
            QMessageBox.warning(
                self,
                "Export Error",
                "Unable to save the PDF. If the file is open, close it and try again.",
            )
            return

        log_event("Admin", "Reports",
                  f"Member statement exported for {member['full_name']} ({staff})",
                  "Success", self.db_path)
        QMessageBox.information(self, "Exported", f"Statement saved to:\n{path}")

    def _generate_society_pdf(self) -> None:
        pdf = self._build_society_pdf()
        if pdf is None:
            return

        path, _ = QFileDialog.getSaveFileName(
            self, "Save Society Summary",
            "SwiftLedger_Society_Summary.pdf", "PDF Files (*.pdf)",
        )
        if not path:
            return

        if not self._write_pdf_to_path(pdf, path):
            QMessageBox.warning(
                self,
                "Export Error",
                "Unable to save the PDF. If the file is open, close it and try again.",
            )
            return

        log_event("Admin", "Reports", "Society summary report exported",
                  "Success", self.db_path)
        QMessageBox.information(self, "Exported", f"Summary saved to:\n{path}")


# ══════════════════════════════════════════════════════════════════════════════
#  Standalone helper – Quick Start Manual (called from wizard / anywhere)
# ══════════════════════════════════════════════════════════════════════════════


def generate_and_open_user_guide(society_data: Dict[str, str]) -> Optional[str]:
    """Generate a branded 'SwiftLedger Quick Start Manual' PDF and open it.

    Args:
        society_data: Dictionary with keys such as *society_name*,
            *security_mode*, *logo_path*, *street*, *city_state*,
            *phone*, *email*, *reg_no*.

    Returns:
        The path to the generated PDF, or ``None`` on failure.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        return None

    society_name = society_data.get("society_name") or "SwiftLedger"
    security_mode = (society_data.get("security_mode") or "password").lower()
    logo_path = society_data.get("logo_path") or ""

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── colours ──────────────────────────────────────────────────────
    DARK = (44, 62, 80)        # #2c3e50
    ACCENT = (52, 152, 219)    # #3498db
    GREEN = (39, 174, 96)      # #27ae60
    WHITE = (255, 255, 255)

    def _footer():
        pdf.set_y(-18)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*DARK)
        pdf.cell(
            0, 8,
            f"Generated by SwiftLedger - Developed by Zabdiel  |  {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            align="C",
        )

    def _section_title(title: str) -> None:
        pdf.set_font("Helvetica", "B", 15)
        pdf.set_text_color(*ACCENT)
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(*ACCENT)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)
        pdf.set_text_color(0, 0, 0)

    def _body(text: str) -> None:
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 7, text)
        pdf.ln(2)

    # ── PAGE 1 – Title Page ──────────────────────────────────────────
    pdf.add_page()

    if logo_path and Path(logo_path).is_file():
        try:
            pdf.image(logo_path, x=80, y=30, w=50)
            pdf.set_y(85)
        except Exception:
            pdf.set_y(50)
    else:
        pdf.set_y(50)

    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*DARK)
    pdf.cell(0, 14, "SwiftLedger", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(*ACCENT)
    pdf.cell(0, 10, "Quick Start Manual", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Official User Guide for {society_name}", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Document generated: {datetime.now().strftime('%B %d, %Y')}", align="C")

    _footer()

    # ── PAGE 2 – Security Setup ──────────────────────────────────────
    pdf.add_page()
    _section_title("1. Security Configuration")

    mode_label = {"pin": "PIN", "password": "Password", "system": "System Authentication"}
    _body(f"Your society has been configured to use {mode_label.get(security_mode, 'Password')} authentication.")
    pdf.ln(2)

    if security_mode == "pin":
        instructions = (
            "PIN Mode\n"
            "- Each time you launch SwiftLedger you will be prompted for your numeric PIN.\n"
            "- PINs should be 4-8 digits long.\n"
            "- Keep your PIN confidential and do not share it.\n"
            "- To change your PIN, go to Settings > Security and update the credential."
        )
    elif security_mode == "system":
        instructions = (
            "System Authentication Mode\n"
            "- SwiftLedger uses your Windows login credentials for access.\n"
            "- No separate PIN or password is required.\n"
            "- Ensure your Windows account is password-protected.\n"
            "- Only the Windows user who completed setup can access the application."
        )
    else:
        instructions = (
            "Password Mode\n"
            "- Each time you launch SwiftLedger you will be prompted for your password.\n"
            "- Use a strong password (8+ characters, mixing letters, numbers and symbols).\n"
            "- Keep your password confidential and do not share it.\n"
            "- To change your password, go to Settings > Security and update the credential."
        )

    _body(instructions)
    _footer()

    # ── PAGE 3 – Core Workflow ────────────────────────────────────────
    pdf.add_page()
    _section_title("2. Core Workflow")

    steps = [
        (
            "Step 1 - Register Members",
            "Navigate to the Members page using the sidebar. Click 'Register Member', "
            "fill in the staff number, full name, and phone number, then confirm. "
            "Each member receives a unique Member ID automatically."
        ),
        (
            "Step 2 - Post Lodgments & Deductions",
            "Open the Savings page. Enter the member's staff number and the amount. "
            "Select 'Lodgment' to credit or 'Deduction' to debit their account. "
            "Every transaction is recorded with a running balance and timestamp."
        ),
        (
            "Step 3 - Apply for Loans",
            "Go to the Loans page. Enter the member's staff number and the requested "
            "principal. SwiftLedger enforces a savings-multiplier rule (default 2x) to "
            "ensure members do not borrow beyond their means. Approved loans generate a "
            "repayment schedule automatically."
        ),
        (
            "Step 4 - Export Audit Logs & Reports",
            "Visit the Reports page to generate branded PDF statements for individual "
            "members or the entire society. The Audit Log page displays every action "
            "performed in the system, providing a complete compliance trail."
        ),
    ]

    for title, body in steps:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*GREEN)
        pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        _body(body)

    _footer()

    # ── PAGE 4 – Letter from the Developer ────────────────────────────
    pdf.add_page()
    _section_title("3. A Letter from the Developer")

    letter = (
        "Dear User,\n\n"
        "Thank you for choosing SwiftLedger to manage your cooperative society's finances. "
        "This application was built with a simple goal: to give cooperative societies a "
        "reliable, transparent, and easy-to-use tool for tracking member savings, loans, "
        "and dividends.\n\n"
        "If you have feature requests, encounter any issues, or simply want to share your "
        "experience, please don't hesitate to reach out.\n\n"
        "Warm regards,\n"
        "ZABDIEL\n"
        "Lead Developer, SwiftLedger\n\n"
        "Contact & Support\n"
        "Email: zabdieldfwesh001@gmail.com\n"
        "GitHub: github.com/fwesh001\n"
    )
    _body(letter)
    _footer()

    # ── Write to temp file and auto-open ──────────────────────────────
    try:
        guides_dir = Path(tempfile.gettempdir()) / "SwiftLedger"
        guides_dir.mkdir(parents=True, exist_ok=True)
        out_path = str(guides_dir / "SwiftLedger_Quick_Start_Manual.pdf")

        content = pdf.output(dest="S")
        data = content.encode("latin-1") if isinstance(content, str) else bytes(content)

        with open(out_path, "wb") as f:
            f.write(data)

        # Auto-open in the default system PDF viewer
        if platform.system() == "Windows":
            os.startfile(out_path)  # type: ignore[attr-defined]
        elif platform.system() == "Darwin":
            subprocess.Popen(["open", out_path])
        else:
            subprocess.Popen(["xdg-open", out_path])

        return out_path

    except Exception:
        return None
